[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/api/*"
  to = "https://api.dostartu.pl/:splat"
  status = 200

[[redirects]]
  from = "/*"
  [headers.values]
		X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self' https://www.duxiana.com"
		X-XSS-Protection = "1; mode=block"
		X-Robots-Tag = "index"
		cache-control = "public, max-age=0, no-cache, no-store, must-revalidate"