export * from "./style"
export type { CheckmarkTextItem } from "./checkmarkTextItem.interface"
export type { CustomerReviewItem } from "./customerReviewItem.interface"
export type { FooterListData } from "./footerListData.interface"
export type { LinkData } from "./linkData.interface"
export type { OpeningData } from "./openingData.interface"
export type { SectionTitleContent } from "./sectionTitleContent.interface"
export type { SpecialDishItem } from "./specialDishItem.interface"
export type { TwoColumnsOptions } from "./twoColumnsOptions.interface"
export type { ColumnOptions } from "./columnOptions.interface"
