export { Header } from "./header/header.component"
export { Footer } from "./footer/footer.component"
export { Layout } from "./layout/layout.component"
export { Seo } from "./seo/seo.component"
export { ImagesGallery } from "./imagesGallery/imagesGallery.component"
export { PlayersList } from "./playersList/playersList.component"
export { Register } from "./register/register.component"
